# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: mcr.microsoft.com/dotnet/core/sdk:3.0

steps:
- task: DotNetCoreCLI@2
  inputs: 
    command: build

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests*.csproj'


- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    targetPath: '$(Pipeline.Workspace)'

# Testing CI
# Another test
# Another test with pull request
# Merger PR from desktop
# changes to yml
# realease 